trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: UseDotNet@2
  inputs:
    version: '9.0.x'
- script: dotnet workload install maui
- script: dotnet restore
- script: dotnet build --configuration Release
